version: "2"

services:
  cb-backend:
    restart: always
    build: backend
    volumes:
      - ./docker-volumes/cb-backend:/usr/src/app/assets
    ports:
      - 3000:3000

  cb-db:
    restart: always
    image: mongo
    volumes:
      - ./docker-volumes/db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dbpassword
