# Build and run the backend containers with:
#   docker-compose build; docker-compose up

# Connect to the mongodb via MongoDB Compass with:
#   mongodb://root:dbpassword@localhost:27017

version: "2"

services:
  cb-backend:
    restart: always
    build: backend
    volumes:
      - ./docker-volumes/cb-backend:/usr/src/app/assets
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production

  cb-db:
    restart: always
    image: mongo
    volumes:
      - ./docker-volumes/db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dbpassword
