# Copy this file and rename the copy to "docker-compose.yml".
# Then, replace the placeholders with your credentials.

# Build and run both containers with:
#   docker-compose build; docker-compose up

# Connect to the db via "MongoDB Compass" with:
#   mongodb://<username>:<password>@localhost:27017

version: "2"

services:
  cb-backend:
    restart: always
    build: backend
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      MONGO_INITDB_ROOT_USERNAME: <username>
      MONGO_INITDB_ROOT_PASSWORD: <password>

  cb-db:
    restart: always
    image: mongo
    volumes:
      - ./docker-volumes/db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: <username>
      MONGO_INITDB_ROOT_PASSWORD: <password>
