version: "2"

services:
  cb-backend:
    restart: always
    build: backend
    volumes:
      - ./docker-volumes/cb-backend:/usr/src/app/assets
    ports:
      - "3000:3000"

  cb-db:
    restart: always
    image: mongo
    volumes:
      - ./docker-volumes/db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dbpassword

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8103:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: guipassword
      ME_CONFIG_MONGODB_URL: mongodb://root:dbpassword@cb-db:27017/
