# Build and run both containers with:
#   docker-compose build; docker-compose up

# Connect to the db via "MongoDB Compass" with:
#   mongodb://<username>:<password>@localhost:27017

# Test the configured environment variables with:
#   docker-compose config

version: "2"

services:
  cb-backend:
    restart: always
    build: backend
    ports:
      - 3000:3000
    environment:
      NODE_ENV: "${NODE_ENV}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"

  cb-db:
    restart: always
    image: mongo
    volumes:
      - ./docker-volumes/db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
